config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :profile, path: 'users/profile'

  resources :posts, path: 'users/posts' do
    patch 'comment/new', to: 'posts#create_comment'
  end



  root to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comment, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post, dependent: :delete_all
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.paginate(page: params[:page], per_page: 3).order('created_at ASC')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[index edit update destroy]
  before_action :post_params, only: %i[create update]

  def index
    @posts = current_user.post.paginate(page: params[:page], per_page: 10)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new; end

  def create
    return unless Post.new(post_params.merge({ user_id: current_user.id })).save!

    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    return unless Post.where(id: params[:id]).first.update(post_params)

    redirect_to posts_path
  end

  def destroy
    return unless Post.where(id: params[:id]).first.destroy

    redirect_to posts_path
  end

  def create_comment
    return unless build_comment

    redirect_to action: 'show', id: params[:post_id]
  end

  private

  def build_comment
    comment = Post.where(id: params[:post_id]).first.comment
    comment.new(body: params[:body], user_id: correct_user.id).save!
  end

  def correct_user
    current_user.nil? ? User.where(username: 'Anonymous/Anonimo').first : current_user
  end

  def post_params
    {
      title: params[:title],
      body: params[:body]
    }
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @user = current_user
  end

  def update
    return unless current_user.update(username: params[:username], email: params[:email])
    
    redirect_to profile_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
<%= render partial: "shared/top_menu"%>

<div class="section-home-page">
    <h1>Home Page</h1>

    <div class="section-all-posts">
        <% @posts.each do |post| %>
            <div class="card-post">
                <div class="card-details">
                <span class="post-created-at"><%= post.user.username + " - " + post.created_at.strftime("%d/%m/%Y") %></span>
                    <h3 class="post-title"><%= (post.title.html_safe).truncate_words(20) %></h3>
                    <span class="post-description"><%= truncate(post.body.html_safe, length: 150)  %></span>
                </div>
                <div class="card-footer">
                    <a href=<%= "/users/posts/#{post.id}" %> >
                        <span class="read-more">Read More</span>
                        <%= fa_icon "arrow-right", title: "Show this post"%>
                    </a>
                </div>
            </div>
        <% end %>

        <%= will_paginate @posts%>
    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MainoBlog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;700;900&display=swap' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render partial: "shared/top_menu"%>

<div class="section-new-posts">
    <h1> New Post </h1>

    <%= render partial: "shared/post_form", :locals => { type: :edit } %>
</div>

app/views/posts/index.html.erb
<%= render partial: "shared/top_menu"%>

<div class="section-posts">
    <h1> Posts </h1>

   

    <div class="section-posts-list">
        <div class="section-top-input">
            <a href=<%= new_post_path %> title="Create a new post">New Post</a>
        </div>

        <% @posts.each do |post| %>
            <div class="post-row">
                <div class="post-title"><%= post.title %></div>

                <div class="post-input-actions">
                    <div class="action">
                        <a data-method="get" href=<%= "/users/posts/#{post.id}" %>>
                            <%= fa_icon "info", title: "Show post" %>
                        </a>
                    </div>

                    <div class="action">
                        <a href=<%= "/users/posts/#{post.id}/edit" %>>
                            <%= fa_icon "edit",title: "Edit post" %>
                        </a>
                    </div>

                    <div class="action">
                        <a data-confirm="Are you sure?" data-method="delete" href=<%= "/users/posts/#{post.id}" %> >
                            <%= fa_icon "trash", title: "Delete post" %>
                        </a>
                    </div>
                </div>
            </div>

        <%end %>

        
    </div>

    <%= will_paginate @posts%>
</div>

app/views/posts/new.html.erb
<%= render partial: "shared/top_menu"%>

<div class="section-new-posts">
    <h1> New Post </h1>

    <%= render partial: "shared/post_form", :locals => { type: :new } %>%>
</div>

app/views/posts/show.html.erb
<%= render partial: "shared/top_menu"%>

<div class="section-show-posts">
    <h1> Show Post </h1>

    <div class="post-content">
        <div class="post-title">
            <span><%= @post.title %></span>
        </div>

        <div class="post-details">
            <div class="info-section">
                <span class="user-info"><%= @post.user.email %></span>
                <span class="post-created-at"><%= @post.created_at.strftime("%d/%m/%Y") %></span>
            </div>

            <div class="post-body">
                <span><%= @post.body %></span>
            </div>
        </div>
    </div>

    <div class="post-comments">
        <ul class="comments-list">
            <% @post.comment.each do |cmd| %>
                <li>
                    <div class="comment-data">
                        <div class="comment-details">
                            <h3> <%= cmd.user.username %> </h3>
                            <span> - <%= cmd.created_at.strftime("%d/%m/%Y") %> </span>
                        </div>
                        <span class="comment-body"><%= cmd.body %></span>                    
                    </div>
                </li>
            <% end %>
        </ul>                    
    </div>

    <div class="comment-input-area">
         <%= form_with url: "/users/posts/#{@post.id}/comment/new", method: :patch do |form| %>
            <div class="inputs">
                <%= form.text_area :query, id: "input-body", name: "body"%>
            </div>

            <%= form.submit "Create new Comment", id: "submit-button"%>
        <% end %>
    </div>
</div>

app/views/shared/_post_form.html.erb
<div class="section-inputs">
    <% if type == :new %>
        <%= form_with url: "/users/posts", method: :post do |form| %>
            <div class="inputs">
                <%= form.label :query, "title", class: "label-input"%>
                <%= form.text_field :query, id: "input-title", name: "title" %>
            </div>
            <div class="inputs">
                <%= form.label :query, "body", class: "label-input"%>
                <%= form.text_area :query, id: "input-body", name: "body" %>
            </div>

            <%= form.submit "Create", id: "submit-button"%>
        <% end %>
    <%else%>
        <%= form_with url: "/users/posts/#{@post.id}", method: :put do |form| %>
            <div class="inputs">
                <%= form.label :query, "title", class: "label-input"%>
                <%= form.text_field :query, id: "input-title", name: "title", value: @post.title %>
            </div>
            <div class="inputs">
                <%= form.label :query, "body", class: "label-input"%>
                <%= form.text_area :query, id: "input-body", name: "body", value: @post.body%>
            </div>

            <%= form.submit "Update", id: "submit-button"%>
        <% end %>
    <% end %>
    
</div>

app/views/shared/_top_menu.html.erb
<div class="section-nav-top">
    <div class="left-buttons">
        <%= link_to "Home", root_path, class: "navigation-buttons" %>
        
        <% unless current_user.nil? %>
            <%= link_to "Profile", profile_index_path, class: "navigation-buttons" %>
            <%= link_to "Posts", posts_path, class: "navigation-buttons" %>
        <%end%>
    </div>
    <div class="right-buttons">
        <% unless current_user.nil? %>
            <span class="user-email"><%= current_user.email %></span>
            <%= button_to "Logout", destroy_user_session_path, method: :delete %>
        <%else%>
            <%= button_to "Login", new_user_session_path, method: :get %>
        <% end %>
        
        
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>